services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app_solucao
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: vite_dev_solucao
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - node_modules_cache:/var/www/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]


volumes: 
  node_modules_cache: